#!/usr/bin/env bash
# T4-D: Produce a fresh gen/apple tree via clean `tauri ios init --ci`
# inside a disposable desktop copy. Never treats gen/apple hand-edits as SoT.
#
# Usage: ios_regenerate_tree.sh <output_gen_apple_dir>
#
# Determinism:
#   - ambient FORCE_COLOR / NO_COLOR / CLICOLOR* are unset for the generator
#   - XcodeGen version must match policy pin
#   - FORCE_COLOR sentinel is restored to literal ${FORCE_COLOR} after generate
#   - Info.ios.plist required keys are merged into generated Info.plist
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:?usage: $0 <output_gen_apple_dir>}"
DESKTOP="$ROOT/apps/desktop"
SRC_TAURI="$DESKTOP/src-tauri"
CANON_PRIVACY="$SRC_TAURI/ios/canonical/PrivacyInfo.xcprivacy"
POLICY="$SRC_TAURI/ios/policy/ios-release.policy.json"
INFO_IOS="$SRC_TAURI/Info.ios.plist"
POST="$ROOT/scripts/ios/ios_postprocess_gen_apple.py"

die() { echo "ios_regenerate_tree: $*" >&2; exit 1; }
[[ -f "$CANON_PRIVACY" ]] || die "missing canonical PrivacyInfo"
[[ -f "$SRC_TAURI/ios/xcodegen/project.yml.template" ]] || die "missing template"
[[ -f "$POLICY" ]] || die "missing policy"
command -v npx >/dev/null 2>&1 || die "npx required"
command -v xcodegen >/dev/null 2>&1 || die "xcodegen required"
command -v python3 >/dev/null 2>&1 || die "python3 required"

EXPECTED_XCODEGEN="$(python3 - <<'PY' "$POLICY"
import json, sys
p = json.load(open(sys.argv[1], encoding="utf-8"))
print(p["xcodegen_version"])
PY
)"
GOT_XCODEGEN="$(xcodegen --version | awk '{print $2}')"
[[ "$GOT_XCODEGEN" == "$EXPECTED_XCODEGEN" ]] \
  || die "XcodeGen version mismatch: got=$GOT_XCODEGEN expected=$EXPECTED_XCODEGEN"

WORK="$(mktemp -d "${TMPDIR:-/tmp}/t4d-regen.XXXXXX")"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT

mkdir -p "$WORK/desktop/src-tauri"
cp "$DESKTOP/package.json" "$WORK/desktop/package.json"
cp "$DESKTOP/package-lock.json" "$WORK/desktop/package-lock.json"
rsync -a \
  --exclude 'gen/' \
  --exclude 'target/' \
  "$SRC_TAURI/" "$WORK/desktop/src-tauri/"
ln -s "$DESKTOP/node_modules" "$WORK/desktop/node_modules"

mkdir -p "$WORK/desktop/src-tauri/gen/apple"
cp "$CANON_PRIVACY" "$WORK/desktop/src-tauri/gen/apple/PrivacyInfo.xcprivacy"

cd "$WORK/desktop"
# Do NOT strip caller FORCE_COLOR here — matrix tests must pass 0/1 through.
# Template uses __PKB_FORCE_COLOR_ARG__ sentinel; postprocess restores literal
# ${FORCE_COLOR}, so generated bytes stay independent of ambient FORCE_COLOR.
npx --no-install tauri ios init --ci --skip-targets-install

cp "$CANON_PRIVACY" "$WORK/desktop/src-tauri/gen/apple/PrivacyInfo.xcprivacy"
if [[ -f "$WORK/desktop/src-tauri/gen/apple/project.yml" ]]; then
  (cd "$WORK/desktop/src-tauri/gen/apple" && xcodegen generate)
fi

python3 "$POST" "$WORK/desktop/src-tauri/gen/apple" "$INFO_IOS"

# Re-run xcodegen ONLY if scheme still wrong after productName — postprocess
# already asserts Coraxis.app; if scheme was generated before productName applied,
# regenerate once then postprocess again.
SCHEME="$WORK/desktop/src-tauri/gen/apple/pkb-desktop.xcodeproj/xcshareddata/xcschemes/pkb-desktop_iOS.xcscheme"
if [[ -f "$SCHEME" ]] && ! grep -q 'BuildableName = "Coraxis.app"' "$SCHEME"; then
  (cd "$WORK/desktop/src-tauri/gen/apple" && xcodegen generate)
  python3 "$POST" "$WORK/desktop/src-tauri/gen/apple" "$INFO_IOS"
fi

rm -rf "$OUT"
mkdir -p "$(dirname "$OUT")"
mkdir -p "$OUT"
cp -R "$WORK/desktop/src-tauri/gen/apple/." "$OUT/"

echo "ios_regenerate_tree: wrote $OUT (xcodegen=$GOT_XCODEGEN)"
